export const allNews = [
	{
		id: 1,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’ 제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: true,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 2,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: true,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 3,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: true,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 4,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: true,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 5,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 6,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 7,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 8,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 9,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
	{
		id: 10,
		teamLogo: '/team-logo/ulsan.svg',
		team: '울산',
		tag: '부상',
		title: '제주SK, FC서울 상대로 다음 달 ‘홈 개막전’',
		content:
			'프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경프로축구 K리그1 제주SK가 다음 달 15일 FC서울과의 홈 개막전을 시작으로 2025시즌에 돌입합니다. 한국프로축구연맹이 발표한 2025시즌 일정표를 보면 제주는 다음 달 15일 오후 3시 30분 제주월드컵경',
		image: '',
		nickname: '닉네임',
		isCertified: false,
		timeAgo: '1시간 전',
		views: '1,098',
		kick: 55,
		comment: 23,
	},
];

export const allCommunities = [
	{
		id: 1,
		title: '(속보) 손흥민 다리 부상 ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 2,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 3,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 4,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 5,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 6,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 7,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 8,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 9,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
	{
		id: 10,
		title: '(속보) 손흥민 다리 부상 ㄷㄷ',
		hasImage: true,
		comment: 20,
		nickname: '닉네임최대여덟자',
		createdAt: '2025.02.26',
		views: '1,023',
		kick: 22,
	},
];
